export const LOAD_DATA = 'APP/LOAD_DATA'
export const LOAD_DATA_SUCCESS = 'APP/LOAD_DATA_SUCCESS'
export const LOAD_DATA_ERROR = 'APP/LOAD_DATA_ERROR'

export const SELECT_ARTICLE = 'APP/SELECT_ARTICLE'
export const SELECT_ORDER = 'APP/SELECT_ORDER'
export const SELECT_TARGET = 'APP/SELECT_TARGET'

export const HIDE_BIG_HEADER = 'APP/HIDE_BIG_HEADER'
export const HIDE_SMALL_HEADER = 'APP/HIDE_SMALL_HEADER'

export const CHANGE_SEARCH_KEY = 'APP/CHANGE_SEARCH_KEY'
export const DO_SEARCH = 'APP/DO_SEARCH'


export const SHOW_FEATURE_IMAGE = 'APP/ARTICLE/SHOW_FEATURE_IMAGE'
export const HIDE_FEATURE_IMAGE = 'APP/ARTICLE/HIDE_FEATURE_IMAGE'

export const SWITCH_LANGUAGE = 'APP/SWITCH_LANGUAGE'

export const INIT_WEB_STATE = 'APP/INIT_WEB_STATE';

export const HOVER  = 'APP/HOVER'


